### ISSUE TITLE
Create check [Desktop and mobile]

### ISSUE THREAD

**Issue by jairolan** [BC-MAY-21-ROR/kata-06-reloj-checador-k06-t01#3]
# REQUIREMENTS
-Private number input screen
-Feedback to employee on successful/failed registration

# DESIGN
Movile
![image](https://user-images.githubusercontent.com/41593304/124791212-78db2d00-df11-11eb-8795-53129ce11f5f.png)
Desktop
![image](https://user-images.githubusercontent.com/41593304/124791288-8c869380-df11-11eb-9406-c811fddedaf5.png)

# Acceptance Criteria
- [x] the worker has to have a way to input his private number
- [x] the user has to have a feedback in case of succes or fail

# Source
https://www.figma.com/file/pC44W2or1frIbX9AfiTEmM/Check-view?node-id=0%3A1

**Comment by Usiel-03A7** [comment]
https://www.figma.com/team_invite/redeem/4RMIs5OhWAsclhgL87PfjV

**Comment by Chavin30** [comment]
Issue done

**Comment by brayandiazc** [comment]
Good design
