### ISSUE TITLE
create company design form [Desktop]

### ISSUE THREAD

**Issue by juliocabrera820** [BC-MAY-21-ROR/kata-06-reloj-checador-k06-t01#30]
# REQUIREMENTS
Design the form to be able to add companies in the application. 

# DESIGN
![image](https://user-images.githubusercontent.com/45634066/124944921-56114d00-dfd3-11eb-845d-4840a5d51713.png)

![image](https://user-images.githubusercontent.com/45634066/124944978-6295a580-dfd3-11eb-9161-8d2a7b235c90.png)

# Acceptance Criteria
List all required acceptance criteria
- [x] Form for companies
- [x] List of companies

**Comment by brayandiazc** [comment]
I liked design, but not colors combined
